apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/part-of: monitoring
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.9.0
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
      - $values/prometheus-stack/kkamji_local_with_thanos.yaml
  - repoURL: https://github.com/KKamJi98/helm-charts
    targetRevision: main
    ref: values
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
      - kkamji_local_with_thanos.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    #    automated:
    #      prune: true
    #      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
